<?php $this->headTitle('All Movies'); ?>

<div class="row">
    <div class="col-md-12">
        <table class="table table-responsive table-striped table-bordered">
            <thead>
            <tr>
                <th>Title</th>
                <th>Director</th>
                <th>Release Date</th>
                <th>Stars</th>
                <th>Synopsis</th>
                <th>Genre</th>
            </tr>
            </thead>
            <tbody>
            <?php /** @var \Movies\Entities\Movie $movie */ ?>
            <?php foreach ($this->movies as $movie): ?>
                <tr>
                    <td><?php print $movie['title']; ?></td>
                    <td><?php print $movie['director']; ?></td>
                    <td><?php print (new \DateTime($movie['release_date']))->format('d/M/Y'); ?></td>
                    <td><?php print implode(', ', $movie['stars']); ?></td>
                    <td><?php print $movie['synopsis']; ?></td>
                    <td><?php print implode(', ', $movie['genre']); ?></td>
                </tr
            <?php endforeach; ?>
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="6"><?php printf('Total movies: %d', count($this->movies)); ?></td>
                </tr>
            </tfoot>
        </table>
    </div>
</div>
